theme: jekyll-theme-cayman
title: Speedos - Uni Augsburg
description: This is our approach to the InformatiCup 2021 competition. Here we will give you a brief introduction to the underlying algorithm as well as the project structure and architecture. Furthermore, we will guide you through the installation process and provide a code example to get you started.
show_downloads: true
